Clean up cros_make_image_bootable and image_to_vm
image_to_vm.sh was running chromeos-setimage.  This script
was not meant to be run outside of a CrOS environment, but
its use here predates the cros_make_image_bootable script.

The change converts the rehashing and imaging over to using
cros_make_image_bootable.  The vm image uses the usb boot target but defaults
the usb drive to sda3.

update_bootloaders is fixed to not clobber existing syslinux
templates.

cros_make_image_bootable flag override support was broken and this fixes it.

TEST=build a new image wtih rootfs checking and without and ensure both woth with image_to_vm.  Also make sure they still boot normally on available hardware.
BUG=chromium-os:5939

Review URL: http://codereview.chromium.org/3189018

Change-Id: Ib4ac25f1a76f25ac7ce4538614ba247df9caea91

diff --git a/bin/cros_make_image_bootable b/bin/cros_make_image_bootable
--- a/bin/cros_make_image_bootable
+++ b/bin/cros_make_image_bootable
@@ -19,12 +19,20 @@ fi
 set -e
 . "$(dirname "$0")/../chromeos-common.sh"  # for partoffset and partsize
 
+if [ $# -lt 2 ]; then
+  echo "Usage: ${0} /PATH/TO/IMAGE IMAGE.BIN [shflags overrides]"
+  exit 1
+fi
+
 BOOT_DESC_FILE="${1}/boot.desc"
 IMAGE="${1}/${2}"
+shift
+shift
+FLAG_OVERRIDES="${@}"
 
 if [ ! -r "${BOOT_DESC_FILE}" ]; then
-  warning "${BOOT_DESC_FILE} cannot be read!"
-  warning "Falling back to command line parsing"
+  warn "${BOOT_DESC_FILE} cannot be read!"
+  warn "Falling back to command line parsing"
   BOOT_DESC="${@}"
 else
   BOOT_DESC="$(cat ${BOOT_DESC_FILE} | tr -s '\n' ' ')"
@@ -92,12 +100,8 @@ DEFINE_string espfs_mountpoint "/tmp/espfs" \
 DEFINE_boolean use_dev_keys ${FLAGS_FALSE} \
   "Use developer keys for signing. (Default: false)"
 
-# Parse command-line flags present after positional args, if any. This needs
-# to happen before we parse boot.desc (otherwise the flags would be lost)
-FLAGS "${@}" || exit 1
-
-# Parse the boot.desc
-eval set -- "${BOOT_DESC}"
+# Parse the boot.desc and any overrides
+eval set -- "${BOOT_DESC} ${FLAG_OVERRIDES}"
 FLAGS "${@}" || exit 1
 
 # Only now can we die on error.  shflags functions leak non-zero error codes,
