use genisoimage where mkisofs unavailable

diff --git a/contrib/create-basic-configdrive b/contrib/create-basic-configdrive
--- a/contrib/create-basic-configdrive
+++ b/contrib/create-basic-configdrive
@@ -69,8 +69,12 @@ if [ $(id -u) -eq 0 ]; then
 fi
 
 # mkisofs tool check
-if ! which mkisofs &>/dev/null; then
-    echo "$0: mkisofs tool is required to create image." >&2
+if which mkisofs &>/dev/null; then
+    MKISOFS="mkisofs"
+elif which genisoimage &>/dev/null; then
+    MKISOFS="genisoimage"
+else
+    echo "$0: mkisofs/genisoimage tool is required to create image." >&2
     exit 1
 fi
 
@@ -171,7 +175,7 @@ CLOUD_CONFIG="${CLOUD_CONFIG/<HOSTNAME>/${HNAME}}"
 
 echo "$CLOUD_CONFIG" > "$CONFIG_FILE"
 
-mkisofs -R -V config-2 -o $CONFIGDRIVE_FILE $WORKDIR
+$MKISOFS -R -V config-2 -o $CONFIGDRIVE_FILE $WORKDIR
 
 echo
 echo
