This starts to fix the scripts so that they load from /usr/lib/crosutils from within the chroot.
It also fixes a number of style issues.

It changes the meaning of cros_workon "list-all" to list all available
packages, and adds "list-live" to list all live packages.

It changes things that load chromeos-common.sh from the installer to
load it from /usr/lib/installer.

BUG=chromium-os:4230
TEST=synced, rebuilt chroot, made packages, made images, built chrome
from source, and wrote an image to a USB stick.

Review URL: http://codereview.chromium.org/6240018

Change-Id: I90c34420af1a64020402bafef8e9e77f56837c02

diff --git a/archive_hwqual b/archive_hwqual
--- a/archive_hwqual
+++ b/archive_hwqual
@@ -6,9 +6,26 @@
 
 # Script to take an archived build result and prepare a hwqual release.
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
-. "$(dirname "$0")/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
 
 # Flags
 DEFINE_string from "" "Directory with build archive (zipname)"
@@ -42,7 +59,7 @@ function main() {
     FLAGS_to="${FLAGS_from}"
   fi
 
-  local script_dir=$(dirname "$0")
+  local script_dir=${SCRIPTS_DIR}
 
   script_dir=$(readlink -f "${script_dir}")
   docgen_dir="autotest/utils/docgen"
diff --git a/bin/cros_make_image_bootable b/bin/cros_make_image_bootable
--- a/bin/cros_make_image_bootable
+++ b/bin/cros_make_image_bootable
@@ -7,21 +7,35 @@
 # Script which ensures that a given image has an up-to-date
 # kernel partition, rootfs integrity hashes, and legacy bootloader configs.
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
-COMMON_PATH="$(dirname "$0")/../common.sh"
-if [ ! -r "${COMMON_PATH}" ]; then
-  echo "ERROR! Cannot find common.sh: ${COMMON_PATH}" 1>&2
-  exit 1
-fi
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils "$(dirname "$(readlink -f "$0")")/..")
+  local path
 
-. "$(dirname "$0")/../common.sh"
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
 
-# Script must be run inside the chroot.
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
+
+# Need to be inside the chroot to load chromeos-common.sh
 assert_inside_chroot
 
+# Load functions and constants for chromeos-install
+. "/usr/lib/installer/chromeos-common.sh" || \
+  die "Unable to load /usr/lib/installer/chromeos-common.sh"
+
 set -e
-. "$(dirname "$0")/../chromeos-common.sh"  # for partoffset and partsize
 
 if [ $# -lt 2 ]; then
   echo "Usage: ${0} /PATH/TO/IMAGE IMAGE.BIN [shflags overrides]"
@@ -41,7 +55,7 @@ if [ ! -r "${BOOT_DESC_FILE}" ]; then
   BOOT_DESC="${@}"
 else
   BOOT_DESC="$(cat ${BOOT_DESC_FILE} | tr -s '\n' ' ')"
-  info "Boot-time configuration for $(dirname ${IMAGE}): "
+  info "Boot-time configuration for $(dirname "${IMAGE}"): "
   cat ${BOOT_DESC_FILE} | while read line; do
     info "  ${line}"
   done
@@ -138,7 +152,7 @@ make_image_bootable() {
   fi
 
   trap "mount_gpt_cleanup" EXIT
-  ${SCRIPTS_DIR}/mount_gpt_image.sh --from "$(dirname ${image})" \
+  "${SCRIPTS_DIR}/mount_gpt_image.sh" --from "$(dirname "${image}")" \
     --image "$(basename ${image})" -r "${FLAGS_rootfs_mountpoint}" \
     -s "${FLAGS_statefulfs_mountpoint}"
 
diff --git a/bin/cros_overlay_list b/bin/cros_overlay_list
--- a/bin/cros_overlay_list
+++ b/bin/cros_overlay_list
@@ -6,24 +6,26 @@
 
 # This script generates the list of board overlays and variants.
 
+# --- BEGIN COMMON.SH BOILERPLATE ---
 # Load common CrOS utilities.  Inside the chroot this file is installed in
-# /usr/lib/crosutils.  Outside the chroot we find it relative to the scripts
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
 # location.
-common_paths="/usr/lib/crosutils $(dirname "$0")/.."
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils "$(dirname "$(readlink -f "$0")")/..")
+  local path
 
-for path in ${common_paths} ; do
-  if [ -f "${path}/common.sh" ] ; then
-    COMMON_SH="${path}/common.sh"
-    break
-  fi
-done
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
 
-if [ -z "${COMMON_SH}" ] ; then
-  error "common.sh not found in search path (${common_paths})"
-  exit 1
-fi
-
-. "${COMMON_SH}"
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
 
 get_default_board
 
diff --git a/bin/cros_package_to_live b/bin/cros_package_to_live
--- a/bin/cros_package_to_live
+++ b/bin/cros_package_to_live
@@ -7,16 +7,28 @@
 # Script to update a running device with an optionally built package out
 # of your build directory
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils "$(dirname "$(readlink -f "$0")")/..")
+  local path
 
-script_root=$(dirname $0)
-if [ -f ${script_root}/../common.sh ] ; then
-  script_root=${script_root}/..
-fi
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
 
-. "${script_root}/common.sh"
-. "${script_root}/remote_access.sh"
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
+
+. "${SCRIPT_ROOT}/remote_access.sh" || die "Unable to load remote_access.sh"
 
 get_default_board
 
@@ -89,8 +101,8 @@ for pkg in $@; do
         echo "Could not find latest built version of ${pkg}"
         exit 1
     fi
-    pkg_dir=$(basename $(dirname $latest_pkg))
-    pkg_name=$(basename $latest_pkg)
+    pkg_dir=$(basename "$(dirname "$latest_pkg")")
+    pkg_name=$(basename "$latest_pkg")
     echo "Installing ${latest_pkg}..."
 
     remote_sh "mktemp -d /tmp/cros_package_to_live.XXXX"
diff --git a/bin/cros_run_vm_test b/bin/cros_run_vm_test
--- a/bin/cros_run_vm_test
+++ b/bin/cros_run_vm_test
@@ -6,9 +6,30 @@
 #
 # Runs a given test case under a VM.
 
-. "$(dirname $0)/../common.sh"
-. "$(dirname $0)/../lib/cros_vm_lib.sh"
-. "$(dirname "$0")/../lib/cros_vm_constants.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils "$(dirname "$(readlink -f "$0")")/..")
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
+
+. "${SCRIPT_ROOT}/lib/cros_vm_lib.sh" || die "Unable to load cros_vm_lib.sh"
+. "${SCRIPT_ROOT}/lib/cros_vm_constants.sh" || \
+  die "Unable to load cros_vm_constants.sh"
 
 MAX_RETRIES=3
 
@@ -73,7 +94,7 @@ retry_until_ssh ${MAX_RETRIES}
 if [ -n "${FLAGS_verify_chrome_version}" ]; then
   info "Verifying version of Chrome matches what we expect."
   if chrome_version_is_valid "${FLAGS_verify_chrome_version}"; then
-    chrome_version_on_vm=$("$(dirname $0)/cros_get_chrome_version" \
+    chrome_version_on_vm=$("${SCRIPTS_DIR}/bin/cros_get_chrome_version" \
         --remote=127.0.0.1 \
         --ssh_port=${FLAGS_ssh_port})
     [[ ${chrome_version_on_vm} == ${FLAGS_verify_chrome_version} ]] || \
@@ -83,7 +104,7 @@ if [ -n "${FLAGS_verify_chrome_version}" ]; then
   fi
 fi
 
-"$(dirname $0)"/../run_remote_tests.sh \
+"${SCRIPTS_DIR}/run_remote_tests.sh" \
     --board=${FLAGS_board} \
     --ssh_port=${FLAGS_ssh_port} \
     --remote=127.0.0.1 \
diff --git a/bin/cros_run_vm_update b/bin/cros_run_vm_update
--- a/bin/cros_run_vm_update
+++ b/bin/cros_run_vm_update
@@ -6,8 +6,28 @@
 #
 # Updates an existing vm image with another image.
 
-. "$(dirname $0)/../common.sh"
-. "$(dirname $0)/../lib/cros_vm_lib.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils "$(dirname "$(readlink -f "$0")")/..")
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
+
+. "${SCRIPT_ROOT}/lib/cros_vm_lib.sh" || die "Unable to load cros_vm_lib.sh"
 
 DEFINE_string payload "" "Full name of the payload to update with."
 DEFINE_string proxy_port "" \
@@ -43,7 +63,7 @@ if [ -n "${FLAGS_proxy_port}" ]; then
   IMAGE_ARGS="${IMAGE_ARGS} --proxy_port=${FLAGS_proxy_port}"
 fi
 
-$(dirname $0)/../image_to_live.sh \
+"${SCRIPTS_DIR}/image_to_live.sh" \
   --for_vm \
   --remote=127.0.0.1 \
   --ssh_port=${FLAGS_ssh_port} \
diff --git a/bin/cros_sign_to_ssd b/bin/cros_sign_to_ssd
--- a/bin/cros_sign_to_ssd
+++ b/bin/cros_sign_to_ssd
@@ -7,11 +7,33 @@
 # Script to resign the kernel partition generated in the output of build_image
 # with SSD keys.
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
-. "$(dirname "$0")/../common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils "$(dirname "$(readlink -f "$0")")/..")
+  local path
 
-. "$(dirname "$0")/../chromeos-common.sh"  # for partoffset and partsize
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
+
+# Need to be inside the chroot to load chromeos-common.sh
+assert_inside_chroot
+
+# Load functions and constants for chromeos-install
+. "/usr/lib/installer/chromeos-common.sh" || \
+  die "Unable to load /usr/lib/installer/chromeos-common.sh"
 
 locate_gpt
 
@@ -44,7 +66,7 @@ fi
 # ../../tests/devkeys/ \
 # /.../build/images/x86-mario/0.8.68.2/chromiumos_test_ssd_image.bin
 
-VBOOT_DIR="$(dirname "$0")/../../platform/vboot_reference"
+VBOOT_DIR="${SRC_ROOT}/platform/vboot_reference"
 if [ ! -d "${VBOOT_DIR}" ]; then
   die "VBOOT DIR NOT FOUND at \'${VBOOT_DIR}\' .."
 fi
diff --git a/bin/cros_start_vm b/bin/cros_start_vm
--- a/bin/cros_start_vm
+++ b/bin/cros_start_vm
@@ -6,9 +6,30 @@
 #
 # Simple wrapper scipt to start a vm using the vm lib.
 
-. "$(dirname $0)/../common.sh"
-. "$(dirname $0)/../lib/cros_vm_lib.sh"
-. "$(dirname "$0")/../lib/cros_vm_constants.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils "$(dirname "$(readlink -f "$0")")/..")
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
+
+. "${SCRIPT_ROOT}/lib/cros_vm_lib.sh" || die "Unable to load cros_vm_lib.sh"
+. "${SCRIPT_ROOT}/lib/cros_vm_constants.sh" || \
+  die "Unable to load cros_vm_constants.sh"
 
 get_default_board
 
diff --git a/bin/cros_stop_vm b/bin/cros_stop_vm
--- a/bin/cros_stop_vm
+++ b/bin/cros_stop_vm
@@ -6,8 +6,28 @@
 #
 # Simple wrapper scipt to stop a vm specified from a pid file.
 
-. "$(dirname $0)/../common.sh"
-. "$(dirname $0)/../lib/cros_vm_lib.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils "$(dirname "$(readlink -f "$0")")/..")
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
+
+. "${SCRIPT_ROOT}/lib/cros_vm_lib.sh" || die "Unable to load cros_vm_lib.sh"
 
 set -e
 
diff --git a/bootperf-bin/bootperf b/bootperf-bin/bootperf
--- a/bootperf-bin/bootperf
+++ b/bootperf-bin/bootperf
@@ -11,14 +11,31 @@
 # chroot environment.
 #
 
-# SCRIPT_DIR="$(cd "$(dirname $0)/.." ; pwd)"
-SCRIPT_DIR=$HOME/trunk/src/scripts
-. "$SCRIPT_DIR/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils "$(dirname "$(readlink -f "$0")")/..")
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
 
 DEFINE_string output_dir "" "output directory for results" o
 DEFINE_boolean keep_logs "$FLAGS_FALSE" "keep autotest results" k
 
-RUN_TEST="$SCRIPT_DIR/run_remote_tests.sh"
+RUN_TEST="$SCRIPTS_DIR/run_remote_tests.sh"
 TEST=server/site_tests/platform_BootPerfServer/control
 TMP_RESULTS="/tmp/bootperf.$(date '+%Y%j%H%M').$$"
 RESULTS_DIR=platform_BootPerfServer/platform_BootPerfServer/results
diff --git a/build_image b/build_image
--- a/build_image
+++ b/build_image
@@ -9,15 +9,39 @@
 # the given target's root with binary packages turned on. This script will
 # build the Chrome OS image using only pre-built binary packages.
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
-. "$(dirname "$0")/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
+  local path
 
-. "$(dirname "$0")/chromeos-common.sh"  # for partoffset
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
+
+# Load functions and constants for chromeos-install
+[ -f /usr/lib/installer/chromeos-common.sh ] && \
+  INSTALLER_ROOT=/usr/lib/installer || \
+  INSTALLER_ROOT=$(dirname "$(readlink -f "$0")")
+
+. "${INSTALLER_ROOT}/chromeos-common.sh" || \
+  die "Unable to load chromeos-common.sh"
+
 locate_gpt
 
 # Script must be run inside the chroot.
-restart_in_chroot_if_needed $*
+restart_in_chroot_if_needed "$@"
 
 get_default_board
 
diff --git a/clean_loopback_devices b/clean_loopback_devices
--- a/clean_loopback_devices
+++ b/clean_loopback_devices
@@ -1,3 +1,4 @@
+#!/bin/sh
 # Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
@@ -7,9 +8,26 @@
 # failures.  This script only affects mountpoints and loopback devices
 # that were created within this chroot.
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
-. "$(dirname "$0")/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
 
 # Script must be run inside the chroot.
 assert_inside_chroot
@@ -24,8 +42,7 @@ OUTPUT_DIR="${FLAGS_output_root}/${FLAGS_board}"
 echo "This will unmount any directory under $OUTPUT_DIR:"
 read -p "Are you sure (y/N)? " SURE
 SURE="${SURE:0:1}" # Get just the first character
-if [ "${SURE}" != "y" ]
-then
+if [ "${SURE}" != "y" ]; then
   echo "Ok, better safe than sorry."
   exit 1
 fi
diff --git a/cros_generate_breakpad_symbols b/cros_generate_breakpad_symbols
--- a/cros_generate_breakpad_symbols
+++ b/cros_generate_breakpad_symbols
@@ -9,12 +9,29 @@
 # NOTE: This script must be run from the chromeos build chroot environment.
 #
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
-. "$(dirname "$0")/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
 
 # Script must be run inside the chroot
-restart_in_chroot_if_needed $*
+restart_in_chroot_if_needed "$@"
 
 get_default_board
 
@@ -39,7 +56,7 @@ function cleanup() {
 # Given path to a debug file, return its text file
 function get_text_for_debug() {
   local debug_file=$1
-  local text_dir=$(dirname ${debug_file#$DEBUG_ROOT})
+  local text_dir=$(dirname "${debug_file#$DEBUG_ROOT}")
   local text_path=${SYSROOT}${text_dir}/$(basename "${debug_file}" .debug)
   echo ${text_path}
 }
diff --git a/cros_generate_update_payload b/cros_generate_update_payload
--- a/cros_generate_update_payload
+++ b/cros_generate_update_payload
@@ -7,12 +7,33 @@
 # Script to generate a Chromium OS update for use by the update engine.
 # If a source .bin is specified, the update is assumed to be a delta update.
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
-. "$(dirname "$0")/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
+
+# Need to be inside the chroot to load chromeos-common.sh
+assert_inside_chroot
 
 # Load functions and constants for chromeos-install
-. "$(dirname "$0")/chromeos-common.sh"
+. "/usr/lib/installer/chromeos-common.sh" || \
+  die "Unable to load /usr/lib/installer/chromeos-common.sh"
 
 SRC_MNT=""
 DST_MNT=""
@@ -233,7 +254,7 @@ else
   fi
   DST_ROOT=$(extract_partition_to_temp_file "$FLAGS_image" 3)
 
-  GENERATOR="$(dirname "$0")/mk_memento_images.sh"
+  GENERATOR="${SCRIPTS_DIR}/mk_memento_images.sh"
 
   CROS_GENERATE_UPDATE_PAYLOAD_CALLED=1 "$GENERATOR" "$DST_KERNEL" "$DST_ROOT"
   mv "$(dirname "$DST_KERNEL")/update.gz" "$FLAGS_output"
diff --git a/cros_mark_branch_as_stable b/cros_mark_branch_as_stable
--- a/cros_mark_branch_as_stable
+++ b/cros_mark_branch_as_stable
@@ -27,9 +27,26 @@
 #
 # Example usage: ./cros_mark_branch_as_stable
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
-. "$(dirname "$0")/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
 
 function is_workon() { xargs grep -lE '^inherit.*cros-workon'; }
 function is_stable() { xargs grep -lE '^KEYWORDS=[^~]*$'; }
@@ -38,8 +55,8 @@ function is_unstable() { xargs grep -lE '^KEYWORDS=.*~'; }
 function get_workon_commit() {
   # Get the latest workon commit associated with an ebuild.
   ebuild="$1"
-  dir=$(dirname $ebuild)
-  CATEGORY=$(basename $(dirname "$dir"))
+  dir=$(dirname "$ebuild")
+  CATEGORY=$(basename "$(dirname "$dir")")
   CROS_WORKON_LOCALNAME=$(basename "$dir")
   CROS_WORKON_SUBDIR=
 
@@ -65,7 +82,7 @@ function get_workon_commit() {
   cd $SRCDIR && git rev-parse HEAD
 }
 
-BLACKLIST_FILE=$(dirname "$0")/cros_mark_as_stable_blacklist
+BLACKLIST_FILE="${SCRIPTS_DIR}/cros_mark_as_stable_blacklist"
 BLACKLIST=$(cat "$BLACKLIST_FILE")
 if [[ -n "$BLACKLIST" ]]; then
   die "$0 does not support cros_mark_as_stable_blacklist"
diff --git a/cros_run_unit_tests b/cros_run_unit_tests
--- a/cros_run_unit_tests
+++ b/cros_run_unit_tests
@@ -10,7 +10,26 @@
 
 # This script requires that you run build_packages first.
 
-. "$(dirname "$0")/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
 
 get_default_board
 
@@ -76,7 +95,7 @@ if [ -z "${FLAGS_package_file}" -a -z "${FLAGS_packages}" ]; then
                   egrep '^chromeos-base' )
 fi
 
-BLACK_LIST_FILE="$(dirname "$0")/unit_test_black_list.txt"
+BLACK_LIST_FILE="${SCRIPTS_DIR}/unit_test_black_list.txt"
 
 if [ "${FLAGS_withdebug}" -eq "${FLAGS_FALSE}" ]; then
   export USE="${USE} -cros-debug"
diff --git a/cros_workon b/cros_workon
--- a/cros_workon
+++ b/cros_workon
@@ -10,12 +10,29 @@
 # is intended to support development. The current source tip is fetched,
 # source modified and built using the unstable 'live' (9999) ebuild.
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
-. "$(dirname "$0")/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
 
 # Script must be run inside the chroot
-restart_in_chroot_if_needed $*
+restart_in_chroot_if_needed "$@"
 get_default_board
 
 DEFINE_string board "${DEFAULT_BOARD}" \
@@ -41,7 +58,6 @@ eval set -- "${FLAGS_ARGV}"
 # eat the workon command keywords: start, stop or list.
 WORKON_CMD=$1
 shift
-
 
 # Board dir config
 
@@ -98,7 +114,8 @@ if [ ! -L "${UNMASK_FILE}" ]; then
 fi
 
 find_keyword_workon_ebuilds() {
-  keyword="${1}"
+  local keyword="${1}"
+  local overlay
 
   local cros_overlays=$("${PORTAGEQCMD}" envvar PORTDIR_OVERLAY)
 
@@ -112,7 +129,7 @@ find_keyword_workon_ebuilds() {
 }
 
 show_workon_ebuilds() {
-  keyword=$1
+  local keyword=$1
 
   find_keyword_workon_ebuilds ${keyword} | \
     sed -e 's/.*\/\([^/]*\)\/\([^/]*\)\/.*\.ebuild/\1\/\2/' | \
@@ -150,6 +167,7 @@ canonicalize_name () {
 canonicalize_names () {
   local atoms=$1
   local names=""
+  local atom
 
   for atom in ${atoms}; do
     local name=$(canonicalize_name "${atom}")
@@ -168,6 +186,7 @@ show_live_ebuilds () {
 # Display ebuilds currently part of the live branch and open for development
 # for any board that currently has live ebuilds.
 show_all_live_ebuilds () {
+  local workon_file
   for workon_file in ${WORKON_DIR}/*; do
     if [ -s "${workon_file}" ]; then
       echo -e "${V_BOLD_GREEN}$(basename ${workon_file}):${V_VIDOFF}"
@@ -177,7 +196,10 @@ show_all_live_ebuilds () {
   done
 }
 
-# This is called only for "cros-workon start". We dont handle the "stop" case since the local changes are ignored anyway since the 9999.ebuild is masked and we dont want to deal with what to do with the user's local changes.
+# This is called only for "cros-workon start". We dont handle the
+# "stop" case since the local changes are ignored anyway since the
+# 9999.ebuild is masked and we dont want to deal with what to do with
+# the user's local changes.
 regen_manifest_and_sync() {
   # Nothing to do unless you are working on the minilayout
   local manifest=${CHROOT_TRUNK_DIR}/.repo/manifest.xml
@@ -185,6 +207,7 @@ regen_manifest_and_sync() {
       return
   fi
 
+  local pkgname
   for pkgname in $(show_live_ebuilds); do
     eval $(${EBUILDCMD} $(${EQUERYCMD} which ${pkgname}) info)
     local srcdir=$(readlink -m ${CROS_WORKON_SRCDIR})
@@ -201,6 +224,7 @@ regen_manifest_and_sync() {
 ebuild_to_live () {
   local atoms=$1
   local atoms_success=""
+  local atom
 
   for atom in ${atoms}; do
     if ! grep -qx "=${atom}-9999" "${WORKON_FILE}" ; then
@@ -219,6 +243,7 @@ ebuild_to_live () {
 ebuild_to_stable () {
   local atoms=$1
   local atoms_success=""
+  local atom
 
   for atom in ${atoms}; do
     if grep -qx "=${atom}-9999" "${WORKON_FILE}" ; then
@@ -236,6 +261,7 @@ ebuild_to_stable () {
 # Run a command on all or a set of repos.
 ebuild_iterate() {
   local atoms=$1
+  local atom
 
   for atom in ${atoms}; do
     info "Running \"${FLAGS_command}\" on ${atom}"
@@ -249,7 +275,7 @@ if [ ${FLAGS_all} = "${FLAGS_TRUE}" ]; then
   case ${WORKON_CMD} in
     start) ATOM_LIST=$(show_workon_ebuilds ${BOARD_KEYWORD});;
     stop|iterate) ATOM_LIST=$(show_live_ebuilds);;
-    list|list-all) ;;
+    list) ;;
     *) die "--all is invalid for the given command";;
   esac
 else # not selected --all
@@ -266,10 +292,11 @@ else # not selected --all
 fi
 
 case ${WORKON_CMD} in
-  start)  ebuild_to_live "${ATOM_LIST}" ;;
-  stop)   ebuild_to_stable "${ATOM_LIST}" ;;
-  list)   [ ${FLAGS_all} = "${FLAGS_FALSE}" ] && show_live_ebuilds || show_workon_ebuilds ${BOARD_KEYWORD} ;;
+  start) ebuild_to_live "${ATOM_LIST}" ;;
+  stop) ebuild_to_stable "${ATOM_LIST}" ;;
+  list) [ ${FLAGS_all} = "${FLAGS_FALSE}" ] && show_live_ebuilds || \
+    show_workon_ebuilds ${BOARD_KEYWORD} ;;
   list-all) show_all_live_ebuilds ;;
-  iterate)ebuild_iterate "${ATOM_LIST}" ;;
+  iterate) ebuild_iterate "${ATOM_LIST}" ;;
   *)      die "$(basename $0): command '${WORKON_CMD}' not recognized" ;;
 esac
diff --git a/start_devserver b/start_devserver
--- a/start_devserver
+++ b/start_devserver
@@ -6,12 +6,30 @@
 
 # Start the Dev Server after making sure we are running under a chroot.
 
-. "$(dirname "$0")/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
 
 # Script must be run inside the chroot if not in 'always serve' mode.
-if [[ "$1" != "--archive_dir" ]]
-then
-  restart_in_chroot_if_needed $*
+if [[ "$1" != "--archive_dir" ]]; then
+  restart_in_chroot_if_needed "$@"
 fi
 
 # Temporary workaround: to start devserver for update engine, pass in args
@@ -23,4 +41,4 @@ if [ -z "${PKG_INSTALL_MASK+x}" ]; then
 fi
 echo PKG_INSTALL_MASK=$PKG_INSTALL_MASK
 
-cd ${GCLIENT_ROOT}/src/platform/dev && python devserver.py $*
+cd ${GCLIENT_ROOT}/src/platform/dev && python devserver.py "$@"
diff --git a/test_image b/test_image
--- a/test_image
+++ b/test_image
@@ -4,9 +4,26 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
-. "$(dirname "$0")/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
 
 # Flags
 DEFINE_string target "x86" \
diff --git a/upload_symbols b/upload_symbols
--- a/upload_symbols
+++ b/upload_symbols
@@ -7,16 +7,30 @@
 # purposes.  This script need only be used to upload release builds
 # symbols or to debug crashes on non-release builds (in which case try
 # to only upload the symbols for those executables involved).
-#
-# NOTE: This script must be run from the chromeos build chroot environment.
-#
 
-# Load common constants.  This should be the first executable line.
-# The path to common.sh should be relative to your script's location.
-. "$(dirname "$0")/common.sh"
+# --- BEGIN COMMON.SH BOILERPLATE ---
+# Load common CrOS utilities.  Inside the chroot this file is installed in
+# /usr/lib/crosutils.  Outside the chroot we find it relative to the script's
+# location.
+find_common_sh() {
+  local common_paths=(/usr/lib/crosutils $(dirname "$(readlink -f "$0")"))
+  local path
+
+  SCRIPT_ROOT=
+  for path in "${common_paths[@]}"; do
+    if [ -r "${path}/common.sh" ]; then
+      SCRIPT_ROOT=${path}
+      break
+    fi
+  done
+}
+
+find_common_sh
+. "${SCRIPT_ROOT}/common.sh" || (echo "Unable to load common.sh" && exit 1)
+# --- END COMMON.SH BOILERPLATE ---
 
 # Script must be run inside the chroot
-restart_in_chroot_if_needed $*
+restart_in_chroot_if_needed "$@"
 
 get_default_board
 
@@ -118,7 +132,7 @@ function main() {
       sudo rm -rf "${DEFAULT_BREAKPAD_ROOT}"
       info "Generating all breakpad symbol files."
       local verbosity=""
-      local generate_script="$(dirname $0)/cros_generate_breakpad_symbols"
+      local generate_script="${SCRIPTS_DIR}/cros_generate_breakpad_symbols"
       [ ${FLAGS_verbose} -eq ${FLAGS_TRUE} ] && verbosity="--verbose"
       if ! "${generate_script}" --board=${FLAGS_board} ${verbosity}; then
         error "Some errors while generating symbols; uploading anyway"
