scripts: fall back to linkage symbols when debug info not present
dump_syms bails if you give it a debug info path and the file there
does not have debug info, instead of falling back to dumping
public/linkage symbols (and more importantly, call frame info).
Give it the chance to redeem itself.

Also, instead of not ever uploading CFI for x86 modules, strip it
for any architecture but only when the file is above some
threshold.

BUG=chromium-os:22373 chromium-os:22741

Change-Id: Iad6981efec537868296a6713b1d9ca0cdb750d28
Reviewed-on: https://gerrit.chromium.org/gerrit/11443
Commit-Ready: Ken Mixter <kmixter@chromium.org>
Reviewed-by: Ken Mixter <kmixter@chromium.org>
Tested-by: Ken Mixter <kmixter@chromium.org>

diff --git a/cros_generate_breakpad_symbols b/cros_generate_breakpad_symbols
--- a/cros_generate_breakpad_symbols
+++ b/cros_generate_breakpad_symbols
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
+# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
@@ -101,16 +101,22 @@ function dump_file() {
   # Dump symbols as root in order to read all files.
   if ! sudo "${DUMP_SYMS}" "${text_file}" "${debug_directory}" > "${SYM_FILE}" \
        2> "${ERR_FILE}"; then
-    # A lot of files (like kernel files) contain no debug information, do
-    # not consider such occurrences as errors.
-    if grep -q "file contains no debugging information" "${ERR_FILE}"; then
-      warn "No symbols found for ${text_file}"
+    # Try dumping just the main file to get public-only symbols.
+    if ! sudo "${DUMP_SYMS}" "${text_file}" > "${SYM_FILE}" 2> "${ERR_FILE}";
+    then
+      # A lot of files (like kernel files) contain no debug information, do
+      # not consider such occurrences as errors.
+      if grep -q "file contains no debugging information" "${ERR_FILE}"; then
+        warn "No symbols found for ${text_file}"
+        return 1
+      fi
+      error "Unable to dump symbols for ${text_file}:"
+      cat "${ERR_FILE}"
+      ANY_ERRORS=1
       return 1
+    else
+      warn "File ${text_file} did not have debug info, using linkage symbols"
     fi
-    error "Unable to dump symbols for ${text_file}:"
-    cat "${ERR_FILE}"
-    ANY_ERRORS=1
-    return 1
   fi
   local file_id=$(head -1 ${SYM_FILE} | cut -d' ' -f4)
   local module_name=$(head -1 ${SYM_FILE} | cut -d' ' -f5)
