Update cros_download_latest_image to work again.
cros_download_latest_image was using cros_gsdcurl, which has stopped working,
even when you use application-specific passwords. I've updated it to use
gsutil instead, which is more supported.

BUG=chromium-os:17512
TEST=Try downloading the latest x86-generic image.

Change-Id: Ia7b0704a8c7ff6897508c44e882f87bc44ccbe28
Reviewed-on: http://gerrit.chromium.org/gerrit/5031
Reviewed-by: Rahul Chaturvedi <rkc@chromium.org>
Tested-by: David James <davidjames@chromium.org>

diff --git a/cros_download_latest_image b/cros_download_latest_image
--- a/cros_download_latest_image
+++ b/cros_download_latest_image
@@ -32,42 +32,36 @@ get_default_board
 
 DEFINE_string board "$DEFAULT_BOARD" \
   "The name of the board to check for images."
-DEFINE_boolean incremental "${FLAGS_FALSE}" "Download incremental build"
+DEFINE_boolean incremental "$FLAGS_FALSE" "Download incremental build"
 
 # Parse command line flags.
 FLAGS "$@" || exit 1
-eval set -- "${FLAGS_ARGV}"
+eval set -- "$FLAGS_ARGV"
 
 # Check on the board that they are trying to set up.
 if [ -z "$FLAGS_board" ] ; then
   die "Error: --board required."
 fi
 
-IMAGES_DIR="${DEFAULT_BUILD_ROOT}/images/${FLAGS_board}"
-
+BUCKET="chromeos-image-archive"
 if [ $FLAGS_board = x86-generic ]; then
   if [ "$FLAGS_incremental" -eq "$FLAGS_TRUE" ]; then
-    URL_PREFIX="https://sandbox.google.com/storage/chromeos-archive/x86-generic-bin"
+    PATH_PREFIX="x86-generic-pre-flight-queue"
   else
-    URL_PREFIX="https://sandbox.google.com/storage/chromeos-archive/x86-generic-rel"
+    PATH_PREFIX="x86-generic-full"
   fi
 else
   die "Unrecognized board: $FLAGS_board"
 fi
 
-read -p "Username [${LOGNAME}]: " GSDCURL_USERNAME
-export GSDCURL_USERNAME
-read -s -p "Password: " GSDCURL_PASSWORD
-echo >&2   # ... because read -s didn't print a newline
-export GSDCURL_PASSWORD
-
-LATEST_BUILD=$(bin/cros_gsdcurl.py -s $URL_PREFIX/LATEST)
+URL_PREFIX="gs://$BUCKET/$PATH_PREFIX"
+LATEST_BUILD=$(gsutil cat $URL_PREFIX/LATEST)
+IMAGES_DIR="$DEFAULT_BUILD_ROOT/images/$FLAGS_board"
 LATEST_IMAGE_DIR="$IMAGES_DIR/$LATEST_BUILD"
 if [ ! -e $LATEST_IMAGE_DIR/chromiumos_base_image.bin ]; then
   mkdir -p $LATEST_IMAGE_DIR
-  bin/cros_gsdcurl.py $URL_PREFIX/$LATEST_BUILD/image.zip -o \
-      $LATEST_IMAGE_DIR/image.zip \
-      || die "Could not download image.zip"
+  gsutil cp "$URL_PREFIX/$LATEST_BUILD/image.zip" \
+      "$LATEST_IMAGE_DIR/image.zip" || die "Could not download image.zip"
   ( cd $LATEST_IMAGE_DIR && unzip -qo image.zip ) \
       || die "Could not unzip image.zip"
 fi
