Use delta_generator from chroot instead of from update_engine directory.
BUG=chromium-os:8185
TEST=Verify delta_generator is in path after emerging hard-host-depends.
     Generate image using delta_generator from chroot.

Change-Id: I03f6260960f472d4ebfc8305945da3cbfc67ff6e

Review URL: http://codereview.chromium.org/4170003

diff --git a/cros_generate_update_payload b/cros_generate_update_payload
--- a/cros_generate_update_payload
+++ b/cros_generate_update_payload
@@ -168,8 +168,8 @@ if [ "$DELTA" -eq "$FLAGS_TRUE" -o "$FLAGS_old_style" -eq "$FLAGS_FALSE" ]; then
   echo "Generating a delta update"
 
   # Sanity check that the real generator exists:
-  GENERATOR="$(dirname "$0")/../platform/update_engine/delta_generator"
-  [ -x "$GENERATOR" ] || die "$GENERATOR doesn't exist, or isn't executable"
+  GENERATOR="$(which delta_generator)"
+  [ -x "$GENERATOR" ] || die "can't find delta_generator"
 
   trap cleanup INT TERM EXIT
   if [ "$DELTA" -eq "$FLAGS_TRUE" ]; then
